# Generated by Django 4.1.6 on 2023-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='новый пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_token',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Токен верификации'),
        ),
    ]
