# Generated by Django 4.1.6 on 2023-02-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель лодки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('length', models.PositiveSmallIntegerField(default=0, verbose_name='Длина в футах')),
                ('year', models.PositiveSmallIntegerField(default=0, verbose_name='Год производства')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена в рублях')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'лодка',
                'verbose_name_plural': 'лодки',
            },
        ),
        migrations.CreateModel(
            name='OldOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(default=0, verbose_name='Год начала владения')),
                ('end_year', models.PositiveSmallIntegerField(default=0, verbose_name='Год окончания владения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.boat')),
            ],
            options={
                'verbose_name': 'старый дряхлый владелец',
                'verbose_name_plural': 'старые дряхлые владельцы',
            },
        ),
    ]
