# Generated by Django 4.1.6 on 2023-02-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created_at',), 'permissions': [('set_publish', 'Can publish article')], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
